<?php 
/*
Copyright (C) 2009 Burak Oguz (barfan) <findikmail@gmail.com>

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

//Software Version
$GLOBALS['version'] = "0.2h";
//Software website
$GLOBALS['website'] = "http://findikproject.org";

//mysqldump command
$GLOBALS['mysqldump'] = "D:\\temp\\xampp\\mysql\\bin\\mysqldump.exe";
// Database hostname
$GLOBALS['DB_HOST'] = "localhost";
// Database user
$GLOBALS['DB_USER'] = "root";
// Database password
$GLOBALS['DB_PASSWORD'] = "";
// Database name
$GLOBALS['DB_DBNAME'] = "findik";
// Log file name
//$GLOBALS['LOG_FILE'] = "/var/log/findik/filter.log";
$GLOBALS['LOG_FILE'] = "c:/filter.log";
// Log file name
$GLOBALS['LIVE_LOG_ROW_COUNT'] = 100;

?>